### ISSUE TITLE
Provide debugging output in plaintext response to webook

### ISSUE THREAD

**Issue by lilith** [imazen/licensing#20]
If the webhook token is correct, we should display a detailed error message upon failure, or an action log upon success. Plain text is fine.

Chargebee provides an excellent harness for re-executing webhooks and looking at responses, which allows us to troubleshoot real problems quickly. empty responses reduce the utility of the replay and test system available. 

Actions we should log 
* Whether we used the provided subscription object or re-fetched it, or whether it was nil
* Whether we updated update_license_id_and_hash
* Sending any email
* Uploading a license file
* Skipping one of the above

I think this would be helpful in troubleshooting customer errors and fixing them in real time.

Let's also output ENV['SOURCE_VERSION'] so we know the commit deployed.

**Comment by VikiAnn** [comment]
Just to clarify, do you want those to be sent as emails like the current [`log_error`](https://github.com/imazen/licensing/blob/heroku/app/controllers/chargebee_controller.rb#L25) does, or were you thinking of logging them with the regular Rails logger so we can see them with `heroku logs`? Or something else?

Currently we can see sent emails in the Rails logs on heroku, I've been running `heroku logs -n 1000` in a clear terminal window so I can search for stuff. Searching for "license_mailer" or "Sent mail" should get you to the relevant output. That seems to be enough to me for the email part at least, but I'll wait for your answer on the other stuff.

**Comment by lilith** [comment]
They should go to both heroku logs and the HTTP response. Primarily, this is for the HTTP response.

**Comment by VikiAnn** [comment]
Oh, do you mean sending a response with data in it back to ChargeBee instead of returning 204 every time? I'm not sure if they store that data, should we try returning a test JSON blob or something for now, just to see if we can get to it later?

**Comment by lilith** [comment]
Yes, text is fine though.

**Comment by VikiAnn** [comment]
OK, I've got some sample text output for now instead of the no content responses for subscription-related webhook events and non-subscription ones. I re-sent the webhook on one of the recent events and it looks like we can inspect the response at the time we re-send it, just not afterwards except in the Rails/Heroku logs (I think that's what you were saying, I just wasn't totally following at first.)

So for the real debugging output, I'm imagining walking through the pieces of code responsible for each of the three main loggable actions (subscription using/fetching, email sending, license file uploading) and constructing a message that indicates whether or not each action happened. Each response for any authorized webhook would include a message something like:

> Subscription [subscription ID] [used provided | re-fetched].
Emails sent:
[subject] to [recipient]
License file [was | was not] uploaded.

Does that sound right?

>Whether we used the provided subscription object or re-fetched it, or **whether it was nil**

When you say it was nil, do you mean log when we got a webhook without a subscription object, or log when we got a subscription object with a nil value (is that a thing?)

**Comment by lilith** [comment]
That sounds right. Re the subscription object, we want to know if we are
skipping the event because it is missing.
